const fs = require("fs");
const chalk = require("chalk");
const purple = chalk.keyword("purple");

class Template {
    constructor({ email, title, mainImgUrl, quickDescription, deployed, userName, repoName, introText, installImgUrl, installTxt, useImgUrl, usageTxt, testTxt, contribTxt, licenseName, yourName, githubProfPicUrl, dependenciesTxt }) {
        this.name = repoName;
        this.text =
            `# ${title}
![Screenshot of ${repoName} by ${userName}](${mainImgUrl})
${quickDescription} A link to the ${deployed ? "deployed version" : "repository"} can be found [here.](${deployed ? "https://" + userName + ".github.io/" + repoName + "/" : "https://github.com/" + userName + "/" + repoName})
## Table of Contents

[Introduction](#introduction)  
[Installation](#installation)  
[Usage](#usage)  
[Tests](#tests)  
[Contributing](#contributing)  
[License](#license)  
[About the Author](#about-the-author)  

## Introduction

![GitHub language count](https://img.shields.io/github/languages/count/${userName}/${repoName}) ![GitHub code size in bytes](https://img.shields.io/github/languages/code-size/${userName}/${repoName}) ![GitHub repo size](https://img.shields.io/github/repo-size/${userName}/${repoName})

${introText}

## Installation
![Installation Image ](${installImgUrl})

${installTxt}

### Dependencies

${dependenciesTxt}

## Usage
![Usage Image](${useImgUrl})

${usageTxt}

## Tests

${testTxt}

## Contributing

${contribTxt} 

## License
### ${licenseName}

![GitHub](https://img.shields.io/github/license/${userName}/${repoName})


## About the Author

${yourName}

![your github profile pic](${githubProfPicUrl})

Github: ${userName}

Github repository: [github.com/${userName}](https://github.com/${userName}/)

Portfolio: [${userName}.github.io/](https://userName.github.io/)

Email: ${email}

README generated by GeneREADME. Original template written with [StackEdit](https://stackedit.io/). Badges provided through shields.io.
`
    }

    geneReadMe() {
        const newDir = `./READMES/${this.name}/`;
        fs.mkdir(newDir, { recursive: true }, (err) => {
            if (err) throw err;
            else {
                fs.writeFile(`${newDir}/README.md`, this.text, (err) => {
                    if (err) throw err;
                    else console.log(`Poof! The ${purple("GeneREADME Genie")} generated your file!`);
                });
            }
        });
    }
}

module.exports = Template;